apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-dev
spec:
  version: 8.3.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
