apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-container-to-kafka
spec:
  type: filebeat
  version: 8.3.3
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
    processors:
      - add_kubernetes_metadata:
    output.kafka:
      hosts:
        [
          "kfk-ingestion-kafka-bootstrap.kafka-dev.svc:9091",
          "kfk-ingestion-kafka-bootstrap.kafka-dev.svc:9092",
          "kfk-ingestion-kafka-bootstrap.kafka-dev.svc:9093",
        ]
      topic: "app.%{[agent.type]}.%{[input.type]}"
      partition.round_robin:
        reachable_only: false
      required_acks: 1
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
